% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Jan-2018 18:19:15
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('dhoscriptplot.mat');

HEADS = 8;

N = 15;

P = 0.5;

STATS = 0.53333333333333333;

T = 1.5707963267948966;

ans = 4.3789389038085939E+17;

c = 1;

i = 15;

script1 = 'This script file plots the function t^2*exp(-t/2)*sin(4*t)';

script2 = 'on the interval [0,T], where T is input by the user.';

t = saveVarsMat.t; % <1x1570 double> too many elements

x = 0.25971789497977282;

y = saveVarsMat.y; % <1x1570 double> too many elements

clear saveVarsMat;
